# Generated by Django 2.2.4 on 2019-08-15 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20, null=True)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20, null=True)),
            ],
        ),
    ]
