# Generated by Django 2.2.4 on 2019-08-23 15:50

from django.db import migrations, models
import django.db.models.deletion
import dongnebug.models


class Migration(migrations.Migration):

    dependencies = [
        ('dongnebug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dongnebug.Complain'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='file',
            field=models.FileField(upload_to='./', validators=[dongnebug.models.validate_file_extension]),
        ),
    ]
